name: Publish to RStudio Connect
description: Publish to RStudio Connect via the rsconnect CLI
author: RStudio Developers
inputs:
  access-type:
    description: Access type to apply to published content
  api-key:
    description: API key generated in RStudio Connect
  dir:
    description: Directory or directories containing the content to publish
    default: .
  force:
    description: Force publish even if up to date
    default: false
  namespace:
    description: Namespace prefix for published paths
  require-vanity-path:
    description: Require setting the vanity path
    default: false
  show-logs:
    description: Show all publishing logs
    default: false
  update-env:
    description: Update content environment variables
    default: true
  url:
    description: RStudio Connect URL
  working-directory:
    description: Directory relative to which the 'dir' argument(s) will be resolved
    default: .
  check-certificate:
    description: Whether to check the SSL certificate
    default: false
runs:
  using: node20
  main: dist/index.js
